USE [master]
GO

/****** Object:  Database [PerfumeDB]    Script Date: 27/04/2023 12:13:00 ******/
CREATE DATABASE [PerfumeDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PerfumeDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PerfumeDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PerfumeDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PerfumeDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PerfumeDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PerfumeDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PerfumeDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PerfumeDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PerfumeDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PerfumeDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PerfumeDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PerfumeDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PerfumeDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PerfumeDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PerfumeDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PerfumeDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PerfumeDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PerfumeDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PerfumeDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PerfumeDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PerfumeDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PerfumeDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PerfumeDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PerfumeDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PerfumeDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PerfumeDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [PerfumeDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PerfumeDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PerfumeDB] SET  MULTI_USER 
GO

ALTER DATABASE [PerfumeDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PerfumeDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PerfumeDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PerfumeDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PerfumeDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PerfumeDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PerfumeDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PerfumeDB] SET  READ_WRITE 
GO


